name = "cf_ai_orbii"
main = "src/worker.ts"
compatibility_date = "2024-11-01"
assets = { directory = "./public" }

[durable_objects]
bindings = [
  { name = "CHAT_SESSIONS", class_name = "ChatSession" }
]

[ai]
binding = "AI"  # available in the Worker as env.AI

[[migrations]]
tag = "v1"
new_sqlite_classes = ["ChatSession"]

